"""empty message

Revision ID: 522f111a0691
Revises: 0248dbb40d14
Create Date: 2019-01-18 14:55:53.317773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522f111a0691'
down_revision = '0248dbb40d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumeres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('mobile_tel', sa.Integer(), nullable=True),
    sa.Column('tel', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumeres'))
    )
    op.create_table('supplieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('mobile_tel', sa.Integer(), nullable=True),
    sa.Column('tel', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('ship_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplieres'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplieres')
    op.drop_table('consumeres')
    # ### end Alembic commands ###
